### ISSUE TITLE
["BUG"] Error log in studio.

### ISSUE THREAD

**Issue by DeimerM** [eduNEXT/eox-tenant#172]
Hi team!

**Describe the bug**

When we access a subdomain of the LMS that does not exist it does not show us a 404 not found page but it takes us to a course listing, this problem was solved when we added the following setting in a yml tutor plugin.

``` yaml

common-env-features: |
       USE_MICROSITE_AVAILABLE_SCREEN: true

```
But when we try to log in to studio we get an error ```404 Client error```.
 
**To Reproduce**
1. Create a nuez environment and configure your tenant.
2. Configure the following yml tutor plugin, don't forget to change the ```SOCIAL_AUTH_EDX_OAUTH2_PUBLIC_URL_ROOT``` with your tenant url.
``` yaml
name: settings
version: 0.1.0
patches:

  common-env-features: |
    USE_MICROSITE_AVAILABLE_SCREEN: true

  openedx-cms-development-settings: |
    ALLOWED_HOSTS = ["*"]
    SESSION_COOKIE_DOMAIN = None
    EOX_CORE_APPEND_LMS_MIDDLEWARE_CLASSES = True
    # Celery's task autodiscovery won't find tasks nested in a tasks package.
    # Tasks are only registered when the module they are defined in is imported.
    FRONTEND_LOGIN_URL = 'https://login.studio.edunext.co/login'
    FRONTEND_LOGOUT_URL = '/logout/'
    # Attempting to solve the mysql connection errors
    # Studio sso
    SOCIAL_AUTH_EDX_OAUTH2_PUBLIC_URL_ROOT = "http://test.local.overhang.io:8000"

  openedx-lms-development-settings: |
     MIDDLEWARE += [
      'eox_core.middleware.PathRedirectionMiddleware',
      'eox_core.middleware.RedirectionsMiddleware',
      #'eox_core.middleware.TPAExceptionMiddleware',
      'eox_tenant.middleware.AvailableScreenMiddleware',
      'eox_tenant.middleware.MicrositeCrossBrandingFilterMiddleware',
     ]
```
3. Attempt to log in to the studio.

**Expected behavior**
We hope that when you try to enter a subdomain that does not exist, it will show the 404 page and allow us to log in to the studio.

**Screenshots**
![Screenshot from 2023-01-27 19-06-53](https://user-images.githubusercontent.com/105317492/215797540-8445315e-f058-4f2c-8460-8a940f857459.png)
picture 1. Error displayed when trying to log into study.

**Who is affected**
This issue affects Saas since we cannot activate the flag to show the 404 not found page when someone tries to enter a subdomain that does not exist.
